title: Noor Ul Wadood Khan
email: your-email@example.com
description: >-
  Personal site and blog of Noor Ul Wadood Khan.
baseurl: ""
url: "https://noorulwadoodkhan.com"
theme: minima
plugins:
  - jekyll-feed
