# Site settings
title: The error log of Becoming 
description: Want to share your thoughts? 
             reach out on X or noorulwadoodkhan[at]gmail[dot]com
theme: minima

# Dark skin
minima:
  skin: dark

# You want your landing page at / and blog at /blog
baseurl: ""      
permalink: pretty

# Timezone
timezone: Asia/Karachi
